# Generated by Django 2.0.6 on 2018-10-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
