# Generated by Django 2.1.1 on 2018-10-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0002_remove_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prognosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.Disease')),
                ('medicines', models.ManyToManyField(to='UserDetails.Medicine')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.Person')),
            ],
        ),
    ]
