# Generated by Django 2.1.1 on 2018-10-19 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0004_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prognosis',
            name='endTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 18, 42, 18, 913855, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='prognosis',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 18, 42, 18, 913855, tzinfo=utc)),
        ),
    ]
