# Generated by Django 2.1.1 on 2018-10-19 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0005_auto_20181020_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 19, 11, 40, 892616, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='person',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bloodGroup',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='endTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 19, 11, 40, 892616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 19, 11, 40, 892616, tzinfo=utc)),
        ),
    ]
