# Generated by Django 2.0.6 on 2018-10-19 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0007_auto_20181020_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AlterField(
            model_name='person',
            name='bloodGroup',
            field=models.CharField(choices=[('B+', 'B+'), ('A+', 'A+'), ('O+', 'O+'), ('AB+', 'AB+'), ('B-', 'B-'), ('A-', 'A-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 20, 2, 23, 892205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='endTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 20, 2, 23, 893744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 20, 2, 23, 893712, tzinfo=utc)),
        ),
    ]
