# Generated by Django 2.0.6 on 2018-10-19 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0008_auto_20181019_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='prognosis',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 21, 49, 54, 885563, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='endTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 21, 49, 54, 887089, tzinfo=utc)),
        ),
    ]
