# Generated by Django 2.0.6 on 2018-10-20 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0009_auto_20181019_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimateEndTime', models.DateField(blank=True, null=True)),
                ('morning', models.IntegerField(default=0)),
                ('afternoon', models.IntegerField(default=0)),
                ('evening', models.IntegerField(default=0)),
                ('night', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicineType',
            field=models.CharField(choices=[('C', 'Capsule'), ('T', 'Tablet'), ('L', 'Liquid'), ('O', 'Other')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 6, 53, 36, 86174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.Disease'),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 6, 53, 36, 88536, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.Medicine'),
        ),
    ]
