# Generated by Django 2.0.6 on 2018-10-20 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0011_auto_20181020_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prognosis',
            name='medicines',
        ),
        migrations.AddField(
            model_name='prognosis',
            name='prescription',
            field=models.ManyToManyField(to='UserDetails.Prescription'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 7, 4, 55, 604123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 7, 4, 55, 606189, tzinfo=utc)),
        ),
    ]
