# Generated by Django 2.0.6 on 2018-10-20 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0013_auto_20181020_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 11, 25, 2, 948185, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.Medicine'),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 11, 25, 2, 950262, tzinfo=utc)),
        ),
    ]
