# Generated by Django 2.1.1 on 2018-10-20 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0014_auto_20181020_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 17, 16, 29, 500077, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='prescription',
            field=models.ManyToManyField(blank=True, to='UserDetails.Prescription'),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2018, 10, 20, 17, 16, 29, 501723, tzinfo=utc)),
        ),
    ]
